deployment:
  tasks:
    - export DEPLOYPATH=/home/athartec/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp index.js $DEPLOYPATH
    - /bin/cp -R styles $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH